[pytest]
addopts = -s -p no:warnings -m "not integration"
log_cli = 1
log_cli_level = INFO
log_cli_format = [pytest][%(asctime)s][%(levelname)s][%(module)s][%(funcName)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_level = INFO
markers =
    integration: marks tests as integration tests requiring Lightstreamer server (deselect with '-m "not integration"')
    manual: marks tests as manual tests that should be skipped in CI
    slow: marks tests as slow (deselect with '-m "not slow"')
spark_options =
    spark.master: local[4]
    spark.sql.catalogImplementation: in-memory
    spark.sql.session.timeZone: UTC
    spark.sql.shuffle.partitions: 4
    spark.default.parallelism: 4
